baseURL = 'https://j4yd3n3.github.io/'
languageCode = 'en-us'
title = 'blog'

[module]
  [[module.imports]]
    path = "github.com/barklan/hugo-dead-simple"

[menus]
  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menus.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

[taxonomies]
  tag = "tags"

[markup.highlight]
  style = "dracula"
  lineNos = false
  codeFences = true

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.passthrough]
  enable = true

[markup.goldmark.extensions.passthrough.delimiters]
  inline = [['$', '$'], ['\\(', '\\)']]
  block = [['$$', '$$'], ['\\[', '\\]']]

[params]
  toc = true
  customCSS = "/css/custom.css"
